### ISSUE TITLE
Clicked event for Engineering cause both Gallery and Engineering button to be activated

### ISSUE THREAD

**Issue by JaeungJayJang** [theplantpsychologist/origami_page#1]
Hello Brandon, Nice to meet you. 😃✋ 
I saw your blog from instagram and while navigating through your website I noticed there's issue on the navigation button where pressing button for "Gallery" does not change the color to gray while pressing button for other navigation tab causes the button to be gray.

if seems that it's because the different styles are applied for each page? like in gallery, **button2** is used while other pages like "engineering" and "Learn" uses **button**.

Maybe you can use `window.location.href` to get the current path, trim to get the page string and apply different style conditionally based on this value?

**Comment by theplantpsychologist** [comment]
Thank you for finding this issue. I've fixed index and gallery to now use the button class like the other pages, and removed the conflicting styles. This also fixed the issue of the page crashing unexpectedly.
